# Generated by Django 4.1.13 on 2024-04-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluffyFriendyApp', '0002_remove_cart_products_cartproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserMember',
        ),
    ]
